### PR TITLE
Update to 27.2

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/emacs-feedstock/pull/51

### CODE REVIEW

**Comment by izahn** [comment]
I think this can be merged @asmeurer @msarahan @notestaff , basically I just dropped patches that were already applied or fixed upstream.

**Comment by asmeurer** [comment]
I think the Apple silicon stuff has to be tested manually. CC @erykoff

**Comment by erykoff** [comment]
Thanks for the ping.  I tested this and sadly it fails.  The problem is that the upstream patch checks for `arm-apple-darwin` but should check for `arm64-apple-darwin`.  This replacement for `0002-apple-silicon-resign-binary.patch` does work, I hope you can put it in on your fork:
```
--- src/Makefile.in.orig	2021-05-05 14:21:56.000000000 -0700
+++ src/Makefile.in	2021-05-05 14:21:59.000000000 -0700
@@ -339,7 +339,7 @@
 
 ## ARM Macs require that all code have a valid signature.  Since pump
 ## invalidates the signature, we must re-sign to fix it.
-DO_CODESIGN=$(patsubst arm-apple-darwin%,yes,@configuration@)
+DO_CODESIGN=$(patsubst arm64-apple-darwin%,yes,@configuration@)
 
 # 'make' verbosity.
 AM_DEFAULT_VERBOSITY = @AM_DEFAULT_VERBOSITY@
```

**Comment by izahn** [comment]
Thanks @asmeurer and I replaced `0002-apple-silicon-resign-binary.patch` with the new one from @erykoff and and all the tests pass. @erykoff do you need to test this again?

**Comment by erykoff** [comment]
Looks good to me.

**Pull request merged**
