### PR TITLE
enable dynamic modules (needed by emacs-jupyter)

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by asmeurer** [comment]
Don't know what this is but if it passes it looks good to merge to me. Reminder that Azure Linux is expected to fail and can be ignored.

**Comment by asmeurer** [comment]
I don't know what the linter is talking about (@conda-forge/core maybe include a link in the message to valid license strings?). I guess we need to switch from "GPL-3.0" to some other formatting of that.

**Comment by notestaff** [comment]
It's to enable https://www.gnu.org/software/emacs/manual/html_node/elisp/Dynamic-Modules.html
needed by https://github.com/dzop/emacs-jupyter

**Comment by beckermr** [comment]
See here: https://spdx.org/licenses/

**Pull request merged**
