### PR TITLE
Master build test

### PR DESCRIPTION
**Pull request by asmeurer**
Test building master as-is (no rerender).

### CODE REVIEW

**Comment by asmeurer** [comment]
It fails here too. So something broke upstream.

**Comment by jakirkham** [comment]
Based on this [line]( https://travis-ci.org/conda-forge/emacs-feedstock/builds/270122482#L8686 ) looks like it was linking to the system `ncurses` before. So maybe the issue is it is now using the `conda-forge` copy of `ncurses`, but there are some adjustments needed.

Mostly likely it is not linking to both `libncurses` and `libtinfo` based on the symbols noted as missing. Old copies and builds of `ncurses` put both in the same library. However the trend is to split them up, which is what we did when adding `ncurses` to `conda-forge`. Would make sure that it know to look for both. Using the `.pc` file with `pkg-config` should help.

**Comment by asmeurer** [comment]
Good catch. So maybe something changed in Travis or in conda build to make it pick up the right one? Are there other packages that are known to be built against the conda-forge ncurses?

I really wish conda-forge/conda-build had better `conda inspect` tooling to prevent accidental linkage of system libraries that are supposed to be coming from conda packages.

**Comment by isuruf** [comment]
> So maybe something changed in Travis or in conda build to make it pick up the right one? 

https://github.com/conda-forge/toolchain-feedstock/pull/11 was merged.

**Comment by jakirkham** [comment]
Agreed that it is probably a `toolchain` change.

`readline` is built against `ncurses`. So is `python` and most other interpreters that allow some user interaction on the command line. Would be pretty difficult to change `ncurses` if that is what you are asking.

**Comment by jakirkham** [comment]
That said, I think it is really that `-ltinfo` needs to be in the linker flags and that is probably it. Using the `pkg-config` file will do this for you. So give either of those a try and if it still doesn't work we can look closer, but I'd be really surprised if that does not fix it.

**Comment by asmeurer** [comment]
I just wanted confirmation that something was actually building against conda-forge ncurses and not all the system ncurses. 

I'll play with the tinfo stuff (unless someone else gets to it first).

**Comment by jakirkham** [comment]
Ah ok. Cool. Yeah other things are.

Alright not planning to dig into this further myself. However if there are more issues, would be happy to take another look.

**Comment by asmeurer** [comment]
I've fixed this by adding `-ltinfo` to LDFLAGS (over at https://github.com/conda-forge/emacs-feedstock/pull/10). I don't know if there is a more correct fix. This strikes me as potentially an upstream bug. 

Closing this because it was just a test build.

**Comment by jakirkham** [comment]
Adding `-ltinfo` is probably correct. Linking to both `libtinfo` and `libncurses`/`libncursesw` is typical and recommended.

**Pull request closed without merging**
