### PR TITLE
Add patches and modifications to allow arm64 native and cross-builds.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Note this has not been verified to create a working cross-build.

### CODE REVIEW

**Comment by erykoff** [comment]
FYI, this builds but does _not_ produce a valid osx-arm64 emacs package.

**Comment by erykoff** [comment]
@conda-forge/emacs @isuruf This PR works for me locally with some not-so-pretty hacks that do the trick.  There are a few components here.  There are patches to allow building natively on osx-arm64 (this is ideal of course, but not possible for us in general).  There are also additional patches and updates to `build.sh` that do the following for cross-building from x86 to arm64:
1) I build the native version of emacs to get working copies of `make-docfile` and `make-fingerprint`
2) I set the configuration variables to the correct values (given the incorrect guesses in the cross-compile configure script)
3) One of the patches modifies the makefile to use the native `make-docfile` and `make-fingerprint` when they are run during the build process.
4) When cross-compiling I turn off the "pdump" method and modify the "nextstep" (!) Makefile to not require the pdump file.

In the end is a working emacs package that I confirm works on the DTK ... with one drawback.  Without the pdump file whenever you start emacs you get a whole dump of info about all the stuff it's compiling (which the pdump file is supposed to do).  Now, on the DTK this takes about a second or so, which is annoying but certainly not catastrophic.  I'd be curious if there's a way to store this in any way on `conda install` / first load, but I'd rather have a working emacs with a 1 second delay than no emacs at all.  (Though, ahem, I will install my native build locally...)

I think this will work until we get native build platform, I certainly believe this is way above the "is this useful at all?" threshold.

Finally, I removed the comment on `build.sh` that the macos version doesn't have GUI support, but this version most certainly does have GUI support (and probably has had for some time).  Although it does seem to be using the Carbon framework, which Apple has promised will go away at some point.

**Comment by asmeurer** [comment]
> In the end is a working emacs package that I confirm works on the DTK ... with one drawback. Without the pdump file whenever you start emacs you get a whole dump of info about all the stuff it's compiling (which the pdump file is supposed to do). Now, on the DTK this takes about a second or so, which is annoying but certainly not catastrophic. I'd be curious if there's a way to store this in any way on conda install / first load, but I'd rather have a working emacs with a 1 second delay than no emacs at all. (Though, ahem, I will install my native build locally...)

Does the pdump go in the install location? Or does it have to redo this every time it starts?

We could add a post-link script that does this. Does it have any additional dependencies or anything? What happens if the user doesn't have permissions to wherever it is writing the file?

> Finally, I removed the comment on build.sh that the macos version doesn't have GUI support, but this version most certainly does have GUI support (and probably has had for some time). 

Oops, I guess I forgot to remove that comment. It used to not work, but I got it working at some point.

> Although it does seem to be using the Carbon framework, which Apple has promised will go away at some point.

I guess that's on upstream.

**Comment by erykoff** [comment]
It seems to have to do this every time it starts.  Which is annoying but not catastrophic.  And it's just loading stuff into memory.  What the pdump file does is allow this to be written to file so that the file is loaded at startup instead of doing all the compiling (and the logging! I wonder if computers are so fast these days it's just as easy to do the compilation as load the memory...it's not like emacs is instant startup anyway.)

If there was an install hook (is there a way of doing something additional at `conda install` time without patching `conda`?) then presumably the user would have write access to the conda directory because otherwise they wouldn't be typing `conda install`.

And yes, the carbon issue is not on us, but may be an issue in the future.

**Comment by chrisburr** [comment]
@erykoff Yes there is: https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html

Though make sure the script is robust against being installed on a different platform. A recent example I worked on is: https://github.com/conda-forge/gdk-pixbuf-feedstock/blob/master/recipe/post-link.sh

**Comment by erykoff** [comment]
Ah, I found that.  Thanks for the useful example!  I'll see if I can get this to work in this case, I'm worried it also requires doing some modifications to the executable which I think would be hard and unjustified for a post-link script.

**Comment by asmeurer** [comment]
I wonder if there are examples of a post-link script writing a file. The docs say that you shouldn't do that. If you do, do you also have to manually remove them in a post-unlink script? Or maybe it would be good to include an empty pdump file in the conda package so that conda knows about the file for when it removes emacs (just make sure the post-link script doesn't write into the hardlink).

**Comment by erykoff** [comment]
Interesting question about files.  First I'm just going to investigate whether it's even technically feasible with the way the emacs builder/loader works.

**Comment by erykoff** [comment]
Okay, with the correct compile flags, I'm able to get it to build, install it on the DTK, and make the bootstrap file there ... provided I play some games with path linking that is _definitely_ not possible in practice.  However, with proof-in-principle that we can do the bootstrap on the DTK I'm going to spend a bit more time on this.

**Comment by erykoff** [comment]
I think this is ready, it isn't the most beautiful but it does work around the emacs build system to successfully cross-compile and to make the pdump file on install.  I have confirmed that this works on the DTK, and I also confirmed that no extra files are created and that uninstall is clean.

**Comment by asmeurer** [comment]
Great. I imagine this will be annoying to keep updated as new emacs releases are made, so we should probably move this over to a native build CI once one becomes available.

**Comment by erykoff** [comment]
AFAICT, these parts of the build system haven't changed in quite some time.  But definitely, once we move to native build CI this will be made happily obsolete!

**Comment by asmeurer** [comment]
Presumably at least some of these patches won't be needed as the next emacs will have them upstreamed, as it will want to support native compilation on ARM OSX itself.

**Pull request merged**
