### PR TITLE
updated to version 25.3 [skip appveyor]

### PR DESCRIPTION
**Pull request by notestaff**

### CODE REVIEW

**Comment by asmeurer** [comment]
Weird error on OS X:

```
  CCLD     temacs
Undefined symbols for architecture x86_64:
  "_tgetent", referenced from:
      _init_tty in term.o
  "_tgetflag", referenced from:
      _init_tty in term.o
  "_tgetnum", referenced from:
      _init_tty in term.o
  "_tgetstr", referenced from:
      _init_tty in term.o
      _term_get_fkeys_1 in term.o
  "_tgoto", referenced from:
      _cmcostinit in cm.o
      _cmgoto in cm.o
  "_tparm", referenced from:
      _tparam in terminfo.o
  "_tputs", referenced from:
      _cmcostinit in cm.o
      _cmgoto in cm.o
      _calccost in cm.o
      _tty_turn_off_insert in term.o
      _string_cost in term.o
      _per_line_cost in term.o
      _tty_clear_to_end in term.o
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by asmeurer** [comment]
Something to do with ncurses (that's where those functions come from)?

**Comment by notestaff** [comment]
I know, but why did it work before?

Maybe, just try adding LDFLAGS=-ltinfo when running configure?

**Comment by asmeurer** [comment]
Since this emacs release apparently didn't change that much, my best guess is that one of the upstream feedstocks broke somehow (likely ncurses). I guess we could try rerendering `master` and seeing if it still builds.

**Comment by asmeurer** [comment]
OK, let's see if Travis builds here https://github.com/conda-forge/emacs-feedstock/pull/15.

**Comment by asmeurer** [comment]
I guess it got broke at https://github.com/conda-forge/emacs-feedstock/pull/12, which had the build removed, but then https://github.com/conda-forge/emacs-feedstock/pull/13 made the build get triggered again (the current build, 25.2, on anaconda.org for Mac is broken).

**Comment by asmeurer** [comment]
I've fixed the build and done the 25.3 update at https://github.com/conda-forge/emacs-feedstock/pull/10

**Pull request closed without merging**
