### PR TITLE
Update emacs to 25.2

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
Damn it, it seems this broke again. I guess I need to finish my cleanups in this feedstock before attempting any updates.

**Comment by asmeurer** [comment]
Only on OS X. Seems to work fine on Linux. For OS X, I guess revert to 25.1 for now, since I can't delete the file from anaconda.org.

**Comment by ocefpaf** [comment]
I can remove the bad binaries for you. 25.2 for OS X, right?

**Comment by asmeurer** [comment]
Yep, just that one.

**Comment by ocefpaf** [comment]
Done.Should be ok now. Let me know if you need anything else.

**Comment by asmeurer** [comment]
Thanks.

**Comment by asmeurer** [comment]
@ocefpaf Can you also delete the 25.1-5 that accidentally got built and uploaded?

**Comment by ocefpaf** [comment]
Done.

**Pull request merged**
